### ISSUE TITLE
Delete API CORS issue from angular UI

### ISSUE THREAD

**Issue by crazykalp** [vbrick/rev-sdk-js#63]
Vbrick delete API is filing with CORS error from Angular UI in chrome browser but same is working fine with postman, can you please help on it

API - https://mbf.rev.vbrick.com/api/v2/videos/${videoId}

headers - httpOptions = { headers: new HttpHeaders({ 'Authorization': `VBrick ${response.token}`, 'Access-Control-Allow-Origin': '*','Access-Control-Allow-Methods': 'POST, GET, OPTIONS, DELETE, PUT','Access-Control-Allow-Credentials': 'true' }) };

**Comment by lukeselden** [comment]
Hi @crazykalp - CORS needs to be [enabled for your Rev tenant](https://github.com/vbrick/rev-client-js#browsers-and-cors-support) - it's disabled by default. Please open up a ticket with [Vbrick Support](https://portal.vbrick.com/open-a-case/) to get this feature enabled for your account. Be sure to indicate if you want CORS enabled for all domains (`*`) or for a specific allow list.

**Comment by crazykalp** [comment]
@lukeselden , Thanks for the quick update, we will contact support team & enable it
